#!/bin/bash
exec 2>&1

echo "Starting Apache Tomcat"

export JAVA_HOME="{{pkgPathFor "core/jdk8"}}"
export TOMCAT_HOME="{{pkg.svc_var_path}}/tc"
export CATALINA_BASE="{{pkg.svc_var_path}}/tc"
export CATALINA_HOME="{{pkg.svc_var_path}}/tc"

source {{pkg.svc_config_path}}/catalina-opts.conf
echo "\$CATALINA_OPTS=$CATALINA_OPTS"

exec ${TOMCAT_HOME}/bin/catalina.sh run

